# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tianwei Zhang
tagline:             'My Website'
description:         ''
url:                 http://tianwei-zhang.github.io
baseurl:             http://tianwei-zhang.github.io/
paginate:            5

# About/contact
author:
  name:              Tianwei Zhang
  url:               www.tianweizhang.info
  email:             kevinzhang122@gmail.com

# Custom vars
version:             1.0.0
