# Dependencies
markdown:            kramdown
highlighter:         rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty

# Setup
title:               'Tianwei'
tagline:             '|Zhang'
description:         'story telling with data'
url:                 http://tianwei-zhang.github.io
baseurl:             http://tianwei-zhang.github.io/
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Tianwei Zhang
  url:               www.tianweizhang.info
  email:             kevinzhang122@gmail.com

# Custom vars
version:             1.0.0
