# Site settings
title: Tianwei's personal page
description: A blog about me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "lhttp://tianwei-zhang.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tianwei Zhang
user_description: "A data scientist interested in changing the world"
user_title: Data Scientist
email: kevinzhang122@gmail.com
#twitter_username: lorem_ipsum
github_username:  tianwei-zhang
gplus_username:  TianweiZhang

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
